<!-- main -->
<div id="main" class="grid_10">

    <h2>heard on the blogs:</h2>
    
    <?php foreach ($this->blogposts as $post): ?>

        <h3><a href="<?php echo $post['url'] ?>"><?php echo $post['title'] ?></a></h3>

        <p class="post-info">Posted by <a href="<?php echo $post['Blog']['url'] ?>"><?php echo preg_replace('/http:\/\//', '', $post['Blog']['url']) ?></a> |
          <span class="date"><?php echo date('Y-m-d', strtotime($post['posted_on'])) ?></span></p>

        <p><?php echo $post['content'] ?></p>

        <p class="postmeta">
          <a href="<?php echo $post['url'] ?>" class="readmore">Read the complete/original post</a>|
          matches <span><?php echo implode(', ', Zend_Json::decode($post['tags'])) ?></span></p>

    <?php endforeach; ?>
<!-- main ends -->
</div>

<!-- right-columns starts -->
<div id="right-columns" class="grid_6">

        <h3>heard on Twitter:</h3>

        <?php foreach ($this->tweets as $post): ?>

            <div class="featured-post">
                <h4><a href="http://twitter.com/<?php echo $post['Twitter']['screen_name'] ?>"><?php echo $post['Twitter']['screen_name'] ?></a></h4>
                <p class="post-info">Posted on <?php echo date('Y-m-d', strtotime($post['posted_on'])) ?> at <?php echo date('H:i:s', strtotime($post['posted_on'])) ?></p>
                <p><?php echo $post['content'] ?></p>
            </div>

        <?php endforeach; ?>


    
<!-- end right-columns -->
</div>
