<?php

/**
 * Default_Model_Base_BlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $guid
 * @property string $title
 * @property string $author
 * @property string $content
 * @property string $url
 * @property timestamp $posted_on
 * @property integer $blog_id
 * @property string $tags
 * @property Default_Model_Blog $Blog
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_BlogPost extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post');
        $this->hasColumn('guid', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('posted_on', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('blog_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Blog as Blog', array(
             'local' => 'blog_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}