<?php

/**
 * Default_Model_Base_Blog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $feed
 * @property string $url
 * @property boolean $live
 * @property Doctrine_Collection $Posts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_Blog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('feed', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('live', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_BlogPost as Posts', array(
             'local' => 'id',
             'foreign' => 'blog_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}