<?php

/**
 * Default_Model_Base_Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tag
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_Tag extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('tag', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}