<?php

/**
 * Default_Model_Base_Twitter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $screen_name
 * @property boolean $live
 * @property Doctrine_Collection $Posts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_Twitter extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('twitter');
        $this->hasColumn('screen_name', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('live', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_TwitterPost as Posts', array(
             'local' => 'id',
             'foreign' => 'twitter_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}