<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<rss version="2.0"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
    xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
    >

<channel>
    <title>Ottawa PHP Community</title>
    <atom:link href="http://ottawaphpcommunity.ca/feed/" rel="self" type="application/rss+xml" />
    <link>http://ottawaphpcommunity.ca</link>
    <description>aggregating the php developers in the Ottawa Valley</description>
    <lastBuildDate>Tue, 16 Jun 2009 01:59:56 +0000</lastBuildDate>

    <language>en</language>
    <?php foreach ($this->data as $item): ?>
      <item>
        <title><?php echo $item['contentType'] . ': ' . $item['title'] ?></title>
        <link><?php echo $item['link'] ?></link>
        <pubDate><?php echo $item['pubDate'] ?></pubDate>
        <guid isPermaLink="false"><?php echo $item['guid'] ?></guid>
        <description><![CDATA[<?php echo $this->escape($item['description']) ?>
        ]]>
        </description>
      </item>
    <?php endforeach; ?>

    </channel>

</rss>
