<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
 <title>Ottawa PHP Community</title>
 <!--[if IE]>
 <script src=" http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->
 <link rel="stylesheet" href="css/opc.css" type="text/css" media="screen" />
</head>
<body>
  <header>
    <h1>Ottawa PHP Community</h1>
    aggregating the php developers in the Ottawa Valley
  </header>
      
  <section id="content">

    <?php echo $this->layout()->content ?>

  </section>

  <footer>
    Brought to you by the <a href="http://www.danceric.net">danceric</a> and the Ottawa php devs.
    Get the <a href="http://github.com/danceric/ottawaphpcommunity/tree/master">source code on GitHub</a>
  </footer>
</body>
</html>
