<?php

/**
 * Default_Model_BlogPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_BlogPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_BlogPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_BlogPost');
    }
    
    public function getLatest($limit=12) 
    {
        return Doctrine_Query::create()
            ->from('Default_Model_BlogPost p')
            ->leftJoin('p.Blog b')
            ->where('b.live = ?', true)
            ->orderBy('p.posted_on DESC')
            ->limit($limit)
            ->execute();
    }
}