<?php

/**
 * Default_Model_TwitterPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_TwitterPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_TwitterPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_TwitterPost');
    }
    
    public function getLatest($limit=22)
    {
        return Doctrine_Query::create()
            ->from('Default_Model_TwitterPost p')
            ->leftJoin('p.Twitter t')
            ->where('t.live = ?', true)
            ->orderBy('p.posted_on DESC')
            ->limit(20)
            ->execute();
    }
}